FROM php:7.4-apache

# Define o diretório de trabalho
WORKDIR /var/www/html

# Copia os arquivos do projeto
COPY index.php /var/www/html/
COPY conexao.php /var/www/html/

# Instala dependências e extensões do PHP
RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-install pdo_mysql mysqli

# Expõe a porta do Apache
EXPOSE 80
